runtime: python39  # Set the appropriate Python runtime version

instance_class: F2

entrypoint: |
    gunicorn -b :$PORT main:app

    # Install required packages from requirements.txt
    - name: gcr.io/appengine-images/python
      args: ['pip', 'install', '-r', 'requirements.txt']

env_variables:
  GOOGLE_CLOUD_PROJECT: light-processor-403701
  TF_FORCE_GPU_ALLOW_GROWTH: 'true'

automatic_scaling:
  target_utilization: 0.65
  min_instances: 1
  max_instances: 10
  min_pending_latency: 30s

resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 10

handlers:
- url: /static
  static_dir: static

- url: /images
  static_dir: images

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /.*
  script: auto

libraries:
- name: flask
  version: 2.0

skip_files:
- ^(.*/)?\.gitignore$
- ^(.*/)?\.git$
- ^(.*/)?\.hg$
- ^(.*/)?\.svn$
- ^(.*/)?CVS$
- ^(.*/)?\..*$
- ^(.*/)?app\.yaml$
- ^(.*/)?requirements\.txt$
- ^(.*/)?venv$
- ^(.*/)?\.vscode$

# Replace "your-project-id" with your actual Google Cloud Project ID
